const now = Date.now()
const h = (n) => new Date(now - n * 60 * 60 * 1000).toISOString()
const m = (n) => new Date(now - n * 60 * 1000).toISOString()

export const MOCK_NEWS = [
  // Breaking
  {
    id: 'mock-01',
    title: 'Terremoto di magnitudo 4.8 avvertito in Centro Italia: verifiche in corso',
    excerpt: 'Una scossa sismica di magnitudo 4.8 è stata registrata alle ore 11:42 con epicentro nei pressi di Rieti. Le autorità stanno effettuando i sopralluoghi. Nessun danno grave segnalato finora.',
    url: '#',
    source: 'ANSA',
    category: 'Italia',
    publishedAt: m(8),
    isBreaking: true,
    image: null,
  },
  {
    id: 'mock-02',
    title: 'G7: accordo raggiunto sulla tassazione minima globale al 15% per le multinazionali',
    excerpt: 'I leader del G7 hanno annunciato un accordo storico sulla global minimum tax. Il premier italiano esprime soddisfazione per il risultato raggiunto.',
    url: '#',
    source: 'Repubblica',
    category: 'Economia',
    publishedAt: m(22),
    isBreaking: true,
    image: null,
  },

  // Italia
  {
    id: 'mock-03',
    title: 'Governo approva decreto legge sull\'intelligenza artificiale: nuove regole per le aziende',
    excerpt: 'Il Consiglio dei Ministri ha approvato il decreto attuativo del Regolamento Europeo sull\'IA. Obblighi di trasparenza per i sistemi ad alto rischio entro 18 mesi.',
    url: '#',
    source: 'Corriere della Sera',
    category: 'Italia',
    publishedAt: h(1),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-04',
    title: 'Roma, nuova linea Metro C: aperta la tratta fino a Piazza Venezia',
    excerpt: 'Inaugurata oggi la tanto attesa estensione della metropolitana C nella Capitale. Il taglio del nastro con la sindaca e il ministro delle Infrastrutture.',
    url: '#',
    source: 'TGCom24',
    category: 'Italia',
    publishedAt: h(2),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-05',
    title: 'Allerta meteo in Sicilia: forti temporali previsti nel weekend',
    excerpt: 'La Protezione Civile ha emesso allerta arancione per temporali intensi nelle province di Palermo, Catania e Messina. Previste precipitazioni fino a 80mm in 24 ore.',
    url: '#',
    source: 'ANSA',
    category: 'Italia',
    publishedAt: h(3),
    isBreaking: false,
    image: null,
  },

  // Mondo
  {
    id: 'mock-06',
    title: 'ONU: accordo globale sul clima, 120 paesi firmano il nuovo trattato di riduzione emissioni',
    excerpt: 'A Ginevra si è conclusa la conferenza climatica con la firma del Patto Verde Globale. L\'impegno è ridurre le emissioni di CO2 del 50% entro il 2035.',
    url: '#',
    source: 'BBC World',
    category: 'Mondo',
    publishedAt: h(1.5),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-07',
    title: 'Tensioni in Medio Oriente: nuovi colloqui di pace mediati dall\'Egitto',
    excerpt: 'Al Cairo è ripreso il tavolo diplomatico con le delegazioni delle principali parti in conflitto. I mediatori egiziani esprimono cauto ottimismo sui progressi.',
    url: '#',
    source: 'Reuters',
    category: 'Mondo',
    publishedAt: h(4),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-08',
    title: 'Elezioni in Francia: exit poll danno il centrosinistra in testa con il 34%',
    excerpt: 'I primi exit poll delle elezioni legislative francesi indicano un vantaggio per la coalizione di sinistra. I mercati reagiscono con volatilità all\'incertezza del risultato.',
    url: '#',
    source: 'BBC World',
    category: 'Mondo',
    publishedAt: h(0.5),
    isBreaking: false,
    image: null,
  },

  // Tech
  {
    id: 'mock-09',
    title: 'OpenAI lancia GPT-5: ragionamento multimodale e contesto da 2 milioni di token',
    excerpt: 'OpenAI ha annunciato GPT-5, il modello che secondo l\'azienda supera i benchmark umani su matematica, codice e ragionamento scientifico. Disponibile via API da oggi.',
    url: '#',
    source: 'TechCrunch',
    category: 'Tech',
    publishedAt: h(2),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-10',
    title: 'Apple WWDC 2026: annunciati i nuovi Vision Pro 2 e iOS 20 con AI integrata',
    excerpt: 'Tim Cook ha svelato Vision Pro 2 con display 16K micro-OLED, peso ridotto del 40% e autonomia da 4 ore. iOS 20 porta un assistente AI on-device senza abbonamento.',
    url: '#',
    source: 'The Verge',
    category: 'Tech',
    publishedAt: h(5),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-11',
    title: 'Google DeepMind: AlphaFold 3 risolve strutture proteiche con accuratezza atomica',
    excerpt: 'Il nuovo modello di DeepMind predice le strutture proteiche con precisione al livello atomico, aprendo la strada a farmaci progettati con AI per malattie finora incurabili.',
    url: '#',
    source: 'Wired',
    category: 'Tech',
    publishedAt: h(6),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-12',
    title: 'Hacker News: il progetto open-source Zed raggiunge 1 milione di sviluppatori',
    excerpt: 'L\'editor di codice scritto in Rust supera il milione di utenti attivi. La community celebra le performance 10x rispetto a VS Code su file di grandi dimensioni.',
    url: '#',
    source: 'Hacker News',
    category: 'Tech',
    publishedAt: h(7),
    isBreaking: false,
    image: null,
  },

  // Economia
  {
    id: 'mock-13',
    title: 'BCE taglia i tassi di 25 punti base: quarta riduzione consecutiva nel 2026',
    excerpt: 'La Banca Centrale Europea ha ridotto il tasso sui depositi al 2,50%. Lagarde: "l\'inflazione è vicina al target, spazio per ulteriori aggiustamenti se i dati lo confermano".',
    url: '#',
    source: 'Il Sole 24 Ore',
    category: 'Economia',
    publishedAt: h(3),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-14',
    title: 'Borsa: Piazza Affari chiude a +1,8%, trascinata da bancari e automotive',
    excerpt: 'Seduta brillante per il FTSE MIB che torna sopra quota 38.000 punti. Bene Unicredit (+3,2%), Stellantis (+2,8%) e Leonardo (+4,1%) dopo la commessa NATO.',
    url: '#',
    source: 'Il Sole 24 Ore',
    category: 'Economia',
    publishedAt: h(8),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-15',
    title: 'Nvidia supera Apple per capitalizzazione: vale 4.200 miliardi di dollari',
    excerpt: 'Il produttore di GPU guidato da Jensen Huang diventa la prima azienda al mondo per capitalizzazione, trainata dalla domanda esplosiva di chip per AI generativa.',
    url: '#',
    source: 'Bloomberg',
    category: 'Economia',
    publishedAt: h(10),
    isBreaking: false,
    image: null,
  },

  // Sport
  {
    id: 'mock-16',
    title: 'Champions League: Real Madrid-Inter 2-1, i nerazzurri eliminati ai supplementari',
    excerpt: 'Una rete di Bellingham al 112\' elimina l\'Inter dalla Champions. Thuram aveva pareggiato all\'89\'. San Siro esplode nel finale, ma non basta. Ottima prestazione degli azzurri.',
    url: '#',
    source: 'Gazzetta dello Sport',
    category: 'Sport',
    publishedAt: m(45),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-17',
    title: 'Mondiali 2026: l\'Italia batte l\'Argentina 1-0 agli ottavi di finale',
    excerpt: 'Gol di Scamacca al 67\'. Gli Azzurri volano ai quarti dove affronteranno la Francia. Spalletti: "partita perfetta, sapevamo come fermare Messi".',
    url: '#',
    source: 'Sky Sport',
    category: 'Sport',
    publishedAt: h(12),
    isBreaking: false,
    image: null,
  },
  {
    id: 'mock-18',
    title: 'Jannik Sinner vince Roland Garros: primo italiano a trionfare sulla terra rossa di Parigi',
    excerpt: 'Sinner sconfigge Alcaraz in cinque set nella finale più lunga della storia del torneo. Un\'impresa storica per il tennis italiano. Il numero 1 del mondo piange in campo.',
    url: '#',
    source: 'Gazzetta dello Sport',
    category: 'Sport',
    publishedAt: h(24),
    isBreaking: false,
    image: null,
  },
]
